# Generated by Django 6.0.5 on 2026-05-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emoji',
            field=models.CharField(blank=True, default='🍔', max_length=10, verbose_name='Эмодзи'),
        ),
    ]
