# Generated by Django 6.0.5 on 2026-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
